// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: protoc-gen-go-http/pb/response/response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// No return standard response if nil
	Custom bool `protobuf:"varint,1,opt,name=custom,proto3" json:"custom,omitempty"`
}

func (x *ResponseOptions) Reset() {
	*x = ResponseOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_go_http_pb_response_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOptions) ProtoMessage() {}

func (x *ResponseOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_http_pb_response_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOptions.ProtoReflect.Descriptor instead.
func (*ResponseOptions) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_http_pb_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseOptions) GetCustom() bool {
	if x != nil {
		return x.Custom
	}
	return false
}

var file_protoc_gen_go_http_pb_response_response_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ResponseOptions)(nil),
		Field:         72295831,
		Name:          "response.options",
		Tag:           "bytes,72295831,opt,name=options",
		Filename:      "protoc-gen-go-http/pb/response/response.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// See `Response` for more details.
	//
	// optional response.ResponseOptions options = 72295831;
	E_Options = &file_protoc_gen_go_http_pb_response_response_proto_extTypes[0]
)

var File_protoc_gen_go_http_pb_response_response_proto protoreflect.FileDescriptor

var file_protoc_gen_go_http_pb_response_response_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d,
	0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x3a, 0x56, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x97, 0xcb, 0xbc, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x4b,
	0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d,
	0x6d, 0x69, 0x78, 0x65, 0x64, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67,
	0x6f, 0x2d, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x3b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_go_http_pb_response_response_proto_rawDescOnce sync.Once
	file_protoc_gen_go_http_pb_response_response_proto_rawDescData = file_protoc_gen_go_http_pb_response_response_proto_rawDesc
)

func file_protoc_gen_go_http_pb_response_response_proto_rawDescGZIP() []byte {
	file_protoc_gen_go_http_pb_response_response_proto_rawDescOnce.Do(func() {
		file_protoc_gen_go_http_pb_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_go_http_pb_response_response_proto_rawDescData)
	})
	return file_protoc_gen_go_http_pb_response_response_proto_rawDescData
}

var file_protoc_gen_go_http_pb_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoc_gen_go_http_pb_response_response_proto_goTypes = []interface{}{
	(*ResponseOptions)(nil),            // 0: response.ResponseOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_protoc_gen_go_http_pb_response_response_proto_depIdxs = []int32{
	1, // 0: response.options:extendee -> google.protobuf.MethodOptions
	0, // 1: response.options:type_name -> response.ResponseOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_go_http_pb_response_response_proto_init() }
func file_protoc_gen_go_http_pb_response_response_proto_init() {
	if File_protoc_gen_go_http_pb_response_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_gen_go_http_pb_response_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_go_http_pb_response_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_go_http_pb_response_response_proto_goTypes,
		DependencyIndexes: file_protoc_gen_go_http_pb_response_response_proto_depIdxs,
		MessageInfos:      file_protoc_gen_go_http_pb_response_response_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_go_http_pb_response_response_proto_extTypes,
	}.Build()
	File_protoc_gen_go_http_pb_response_response_proto = out.File
	file_protoc_gen_go_http_pb_response_response_proto_rawDesc = nil
	file_protoc_gen_go_http_pb_response_response_proto_goTypes = nil
	file_protoc_gen_go_http_pb_response_response_proto_depIdxs = nil
}
